###########################
# CORE HASS CONFIGURATION #
###########################

homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 25
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include includes/customize.yaml
http:
  api_password: !secret http_password
  base_url: !secret base_url
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
updater:
  include_used_components: true
frontend:
cloud:
config:
discovery:
conversation:
logbook:

####################################
# Logging and Histoy Configuration #
####################################
history:
  exclude:
    domains:
      - automation
      - updater
      - zone
      - zwave
recorder:
  purge_interval: 1
  purge_keep_days: 7
  exclude:
    domains:
      - automation
      - updater
      - zone
      - zwave
logger:
  default: error
system_log:
  max_entries: 150

########################
# Z-Wave Configuration #
########################

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
  polling_interval: 40000
 
#######################
# Other Configuration #
########################
sun:
ffmpeg:
################################
# Text to Speech Configuration #
################################
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 3600

#######################
# MQTTT Configuration #
#######################
mqtt:
  broker: 192.168.1.250
  username: !secret mqttt_user
  password: !secret http_password

######################
# Nest Configuration #
######################
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  sensors:
    monitored_conditions:
      - co_status
      - smoke_status
      - battery_health
      
#######################
# IFTTT Configuration #
#######################
ifttt:
  key: !secret ifttt_key

############################
# Home Alarm Control Panel #
############################
alarm_control_panel:
  - platform: manual_mqtt
    name: Home_Alarm
    code: !secret alarm_code
    pending_time: 20
    trigger_time: 15
    state_topic: home/alarm
    command_topic: home/alarm/set
    armed_home:
      pending_time: 0

#########################
# Weather Configuration #
#########################
weather:
  - platform: openweathermap
    api_key: !secret weather_api
    
###################
# Device Tracking #
###################

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 50
    track_new_devices: false
  - platform: nmap_tracker
    track_new_devices: false
    hosts: 192.168.1.0/24
    home_interval: 60
    exclude:
      - 192.168.1.250
  - platform: bluetooth_tracker
    track_new_devices: false

############
# Includes #
############

# Direcrtories
automation: !include_dir_merge_list automations/

group: !include_dir_merge_named includes/groups/
notify: !include_dir_merge_list includes/notify/
#switch: !include_dir_merge_list includes/switchs/
sensor: !include_dir_merge_list includes/sensors/
#script: !include_dir_merge_list includes/scripts/
#shell_commands: !include_dir_merge_list scripts/shell/

# Single Files
input_boolean: !include includes/input_boolean.yaml
#media_player: !include includes/mediaplayer.yaml
#zone: !include includes/zones.yaml
#remote: !include includes/remotes.yaml
#camera: !include includes/cameras.yaml
sabnzbd: !include includes/sabnzb.yaml
