title: Carpenters Home

background: center / cover no-repeat url("/lovelace/background.jpg") fixed

views:

  - title: Home
    id: home
    background: center / cover no-repeat url("/lovelace/background.jpg") fixed
    cards:
      - type: entity-filter
        entities:
          - sensor.downstairs_nest_protect_smoke_status
          - sensor.upstairs_nest_protect_smoke_status
          - sensor.upstairs_nest_protect_co_status
          - sensor.downstairs_nest_protect_co_status
          - sensor.upstairs_nest_protect_battery_health
          - sensor.downstairs_nest_protect_battery_health
        state_filter:
          - 'Warning'
          - 'Emergency'
          - 'Replace'
      - type: entities
        entities:
          - device_tracker.homeassistant_mc
          - device_tracker.homeassistant_sc
      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
      - type: gauge
        entity: sensor.lux
        title: Light
        unit_of_measurement: lux
        min: 0
        max: 1000
        red: 20
        green: 400
        yellow: 50
      - type: weather-forecast
        entity: weather.openweathermap
      
  - title: Outside
    id: outside
    cards:
      - type: entities
        entities:
          - light.front
          - lock.gate

  - title: Lounge
    id: lounge
    background: center / cover no-repeat url("/lovelace/background.jpg") fixed
    cards:
      - type: entities
        entities:
          - light.lounge
      - type: entities
        entities:
          - entity: media_player.lounge_kodi
            name: Lounge Media Center
          - entity: media_player.lounge_tv
            name: Lounge TV

  - title: Bathroom
    id: bathroom
    cards:
      - type: entities
        entities:
          - light.bathroom
          - switch.bathroom_extractor

  - title: Izzy
    id: izzy
    cards:
      - type: entities
        entities:
          - light.izzy_light
          - switch.fish_tank
          
  - title: Office
    id: office
    cards:
      - type: entities
        entities:
          - switch.office
          
  - icon: mdi:crosshairs-gps
    title: Travel
    id: travel
    cards:
      - type: gauge
        entity: sensor.to_roedean
        title: Mins
        unit_of_measurement: min
        min: 0
        max: 80
        red: 60
        green: 0
        yellow: 50
      - type: entities
        entities:
          - device_tracker.homeassistant_mc
          - device_tracker.homeassistant_sc

  - icon: mdi:server-minus
    title: Home Assistant
    id: homeassistant
    cards:
      - type: gauge
        entity: sensor.cpu_usage
        title: CPU
        unit_of_measurement: '%'
        min: 0
        max: 100
        red: 75
        yellow: 50
        green: 0
      - type: gauge
        entity: sensor.disk_use_percent
        title: Disk
        unit_of_measurement: '%'
        min: 0
        max: 100
        red: 75
        yellow: 50
        green: 0
      - type: gauge
        entity: sensor.memory_use_percent
        title: RAM
        unit_of_measurement: '%'
        min: 0
        max: 100
        red: 75
        yellow: 50
        green: 0
      - type: entities
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
          - sensor.ssl_certificate_expiry
