# Internet Sensors

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: haveibeenpwned
  email:
    - !secret mmv
    - !secret mdhcd
    - !secret mwork
    - !secret mgoogle
    - !secret hgoogle
    - !secret smv
