# Travel Time

- platform: google_travel_time
  api_key: !secret google_travel
  origin: !secret home_pc
  destination: !secret mwork_pc
  name: To Roedean

- platform: google_travel_time
  api_key: google_travel
  origin: device_tracker.homeassistant_mc
  destination: !secret home_pc
  name: To Home Max

- platform: google_travel_time
  api_key: google_travel
  origin: device_tracker.homeassistant_sc
  destination: !secret home_pc
  name: To Home Sophie
