# Media Players

- platform: kodi
  host: !secret kodi_lounge
  name: Lounge_Kodi
  username: !secret kodi_user
  password: !secret kodi_pass

- platform: kodi
  host: !secret kodi_bedroom
  name: Bedroom_Kodi
  username: !secret kodi_user
  password: !secret kodi_pass

#- platform: kodi
#  host: !secret kodi_dinningroom
#  name: Dinning Room
#  username: !secret kodi_user
#  password: !secret kodi_pass

#- platform: kodi
#  host: !secret kodi_kitchen
#  name: Kitchen
#  username: !secret kodi_user
#  password: !secret kodi_pass

- platform: webostv
  host: 192.168.1.240
  name: Lounge_TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 7C:1C:4E:03:A1:49
  customize:
    sources:
      - livetv
      - youtube
      - MediaCentre
      - netflix

- platform: samsungtv
  host: 192.168.1.241
  Name: Dinning_TV
  mac: 00:00:00:00:00:00
  
- platform: squeezebox
  host: 192.168.1.251
  username: !secret lms_user
  password: !secret lms_pass

- platform: cast
